### ISSUE TITLE
"reorderBinary" not resolved from current namespace (phylobase)

### ISSUE THREAD

**Issue by JaydenM-C** [fmichonneau/phylobase#10]
Hi!

When subsetting a tree

`geospiza_subset <- phylobase::subset(geospiza, tips.include = c("Platyspiza", "olivacea", "pauper", "difficilis"))`

I receive the following error:

`Error in .C("reorderBinary", descendantNew, root, ancestor, left, right,  : 
  "reorderBinary" not resolved from current namespace (phylobase)`

The same error is produced when attempting to coerce my own phylo object into the phylo4 class with `as(phylo_object, "phylo4")`. 

I'm not expert enough to know exactly what's happening, but my reading of [this old R help thread](http://r.789695.n4.nabble.com/question-re-error-message-package-error-quot-functionName-quot-not-resolved-from-current-namespace-td4663892.html) (see Martin Morgan's response in particular) suggests it's a problem with the package's namespace.

Cheers,
Jayden

**Comment by fmichonneau** [comment]
hi @JaydenM-C thanks for your report. I don't seem to be able to reproduce this. My guess would be that it's related to an issue with packages compiled under a different version of R from the one you are using. Try to reinstall both ape and phylobase:

```r
install.packages(c("ape", "phylobase"))
```

and restart R. Please report back to let me know if it fixed the issue. If it does not, please attach the output of your `sessionInfo()`.

**Comment by JaydenM-C** [comment]
Thank you so much for getting back to me on this. Reinstalling and restarting R has indeed fixed the issue (I'm sorry that I didn't think to try this before hassling you about it!). Thanks for your help!
