### ISSUE TITLE
upcoming RNeXML release introduces a new warning

### ISSUE THREAD

**Issue by cboettig** [fmichonneau/phylobase#11]
Hey @fmichonneau , @hlapp and I are planning a new RNeXML release, which I'm afraid introduces a new WARNING to the automated check of `phylobase`:

```
New result: WARNING
  Found the following significant warnings:
    Warning: replacing previous import ‘RNeXML::slot<-’ by ‘methods::slot<-’ when loading ‘phylobase’
    Warning: replacing previous import ‘RNeXML::slot’ by ‘methods::slot’ when loading ‘phylobase’
```

I believe this warning actually has no impact on the behavior of `phylobase`, but I'm not sure how / if it can be suppressed, since it is tied up in S4 internals. @hlapp has looked at this more recently and might have some good suggestions?

**Comment by hlapp** [comment]
I suppose this is because `methods` is being imported in whole in Phylobase.
