### ISSUE TITLE
ERROR package or namespace load failed for ‘phylobase’ 

### ISSUE THREAD

**Issue by RominaSSBatista** [fmichonneau/phylobase#8]
I've tried many ways to install the phylobase package. I am always getting the same erros.
Error: package or namespace load failed for ‘phylobase’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘uuid’

I am installing in a R version 3.4.0 (2017-04-21).
My local machine is a OS X El Capitan v.10.11.6

I will appreciate any help.

**Comment by fmichonneau** [comment]
hi @RominaSSBatista 

it looks like there is a problem with one of the package dependency. Can you try to install the package "uuid"? From the R command line:

```r
install.packages("uuid")
```

Please let me know if it works or not
